service: frenchwhaling
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    tags:
      Application: frenchwhaling
  stackTags:
    Application: frenchwhaling
  tags:
    Application: frenchwhaling

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  stats:
    handler: bin/stats
    events:
      - http:
          cors: true
          path: stats
          method: get
