service: frenchwhaling
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    tags:
      Application: frenchwhaling
  stackTags:
    Application: frenchwhaling
  tags:
    Application: frenchwhaling
  iamRoleStatements:
    - Effect: Allow
      Action: "dynamodb:*Item"
      Resource:
      - Fn::GetAtt: SubscribersTable.Arn
      - Fn::GetAtt: SubscriberEventsTable.Arn
    - Effect: Allow
      Action:
      - "s3:GetObject"
      - "s3:PutObject"
      - "s3:ListBucket"
      Resource:
      - Fn::GetAtt: SubscribersBucket.Arn
      - Fn::Join:
        - ''
        - - Fn::GetAtt: SubscribersBucket.Arn
          - '/*'
    - Effect: Allow
      Action: "sns:Publish"
      Resource:
        Ref: SNSTopic

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  login:
    handler: bin/login
    environment:
      APPLICATION_ID: ${file(.env.live.json):APPLICATION_ID}
      SIGNING_SECRET: ${file(.env.live.json):SIGNING_SECRET}
      TOPIC_ARN:
        Ref: SNSTopic
    events:
      - http:
          cors: true
          path: /login
          method: get

  refresh:
    handler: bin/refresh
    memorySize: 256
    reservedConcurrency: 1
    environment:
      APPLICATION_ID: ${file(.env.live.json):APPLICATION_ID}
    events:
    - sns:
        filterPolicy:
          Type:
          - Refresh
        arn:
          Fn::Join:
            - ':'
            - - 'arn:aws:sns'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'frenchwhaling-events'
        topicName: frenchwhaling-events

resources:
  Resources:
    SubscribersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: frenchwhaling-subscribers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
        - AttributeName: "AccountID"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "AccountID"
          KeyType: "HASH"
    
    SubscriberEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: frenchwhaling-subscriber-events
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: "AccountID"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "AccountID"
          KeyType: "HASH"
        - AttributeName: "Timestamp"
          KeyType: "RANGE"
        GlobalSecondaryIndexes:
        - IndexName: "AccountID-index"
          KeySchema:
          - AttributeName: "AccountID"
            KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
    
    SubscribersBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: frenchwhaling-subscribers
        VersioningConfiguration:
          Status: Enabled

    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: frenchwhaling-events
        DisplayName: frenchwhaling-events