service: whaling
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    tags:
      Application: whaling
  stackTags:
    Application: whaling
  tags:
    Application: whaling
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*Item
      - dynamodb:Scan
      Resource:
      - Fn::GetAtt: SubscribersTable.Arn
      - Fn::GetAtt: SubscriberEventsTable.Arn
    - Effect: Allow
      Action:
      - "s3:GetObject"
      - "s3:PutObject"
      - "s3:PutObjectAcl"
      - "s3:ListBucket"
      Resource:
      - Fn::GetAtt: SubscribersBucket.Arn
      - Fn::Join:
        - ''
        - - Fn::GetAtt: SubscribersBucket.Arn
          - '/*'
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        arn:aws:s3:::whaling.in.fkn.space/*
    - Effect: Allow
      Action: "sns:Publish"
      Resource:
        Ref: SNSTopic
    - Effect: Allow
      Action: "cloudwatch:PutMetricData"
      Resource: "*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  login:
    handler: bin/login
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SIGNING_SECRET: ${file(.env.live.yml):SigningSecret}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
      TOPIC_ARN:
        Ref: SNSTopic
    events:
      - http:
          cors: true
          path: /login
          method: get
    
  click:
    handler: bin/click
    environment:
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
    events:
      - http:
          cors: true
          path: /click
          method: post

  requestRefresh:
    handler: bin/requestRefresh
    memorySize: 256
    timeout: 3
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SIGNING_SECRET: ${file(.env.live.yml):SigningSecret}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
      TOPIC_ARN:
        Ref: SNSTopic
    events:
    - http:
        cors: true
        path: /subscribers/{accountId}/refresh
        method: get

  manualRefresh:
    handler: bin/refresh
    memorySize: 512
    timeout: 10
    reservedConcurrency: 3
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
    events:
    - sns:
        filterPolicy:
          Type:
          - ManualRefresh
        arn:
          Fn::Join:
            - ':'
            - - 'arn:aws:sns'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'whaling-events'
        topicName: whaling-events


  refresh:
    handler: bin/refresh
    memorySize: 256
    timeout: 600
    reservedConcurrency: 4
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
    events:
    - sns:
        filterPolicy:
          Type:
          - Refresh
        arn:
          Fn::Join:
            - ':'
            - - 'arn:aws:sns'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'whaling-events'
        topicName: whaling-events
  
  schedule:
    handler: bin/schedule
    memorySize: 256
    timeout: 90
    reservedConcurrency: 1
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
      TOPIC_ARN:
        Ref: SNSTopic
    events:
      - schedule: rate(2 minutes)
  
  generateGlobalStats:
    handler: bin/generateGlobalStats
    memorySize: 2048
    timeout: 300
    environment:
      APPLICATION_ID: ${file(.env.live.yml):ApplicationID}
      SENTRY_DSN: ${file(.env.live.yml):SentryDsn}
    events:
      - schedule: rate(1 hour)

resources:
  Resources:
    SubscribersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: whaling-subscribers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
        - AttributeName: "AccountID"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "AccountID"
          KeyType: "HASH"
    
    SubscriberEventsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: whaling-subscribers-events
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: "AccountID"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "N"
        KeySchema:
        - AttributeName: "AccountID"
          KeyType: "HASH"
        - AttributeName: "Timestamp"
          KeyType: "RANGE"
        GlobalSecondaryIndexes:
        - IndexName: "AccountID-index"
          KeySchema:
          - AttributeName: "AccountID"
            KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
    
    SubscribersBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: whaling-subscribers

    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: whaling-events
        DisplayName: whaling-events
